on:
  workflow_call:
  # Permissions inherited from caller workflow

permissions: {}

jobs:
  sslib-main:
    name: Test securesystemslib main branch (not a merge blocker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TUF
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            requirements/*.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python3 -m pip install --constraint requirements/build.txt tox

      - name: Run tox
        run: tox -e with-sslib-main
